
version: '3'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      API: "http://api:5000/"
    networks:
      - api_weather

networks:
  api_weather:
    external: true