version: '3'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      API: "http://api:5000/"
    networks:
      - api_weather
    depends_on: 
      - database
  database:
    image: postgresql
    ports:
      - 5432:5432

networks:
  api_weather:
    external: true